CREATE TABLE [dbo].[Retransfer] (
    [RetransferId]            INT            IDENTITY (1, 1) NOT NULL,
    [BaseDocumentId]          INT            NULL,
    [RetransferDate]          DATE           NULL,
    [DealInfo]                NVARCHAR (50)  NULL,
    [Comment]                 NVARCHAR (MAX) NULL,
    [SenderOrganizationId]    INT            NULL,
    [SenderTin]               NVARCHAR (50)  NULL,
    [SenderName]              NVARCHAR (255) NULL,
    [SenderLocation]          NVARCHAR (500) NULL,
    [SenderBankName]          NCHAR (255)    NULL,
    [SenderSupplyLocation]    NVARCHAR (500) NULL,
    [SenderAccountNumber]     NVARCHAR (50)  NULL,
    [SenderHeadName]          NVARCHAR (50)  NULL,
    [SenderAccountantName]    NVARCHAR (50)  NULL,
    [SenderResponsibleName]   NVARCHAR (50)  NULL,
    [ReceiverOrganizationId]  INT            NULL,
    [ReceiverTin]             NVARCHAR (50)  NULL,
    [ReceiverName]            NVARCHAR (255) NULL,
    [ReceiverLocation]        NVARCHAR (500) NULL,
    [ReceiverBankName]        NCHAR (255)    NULL,
    [ReceiverSupplyLocation]  NVARCHAR (500) NULL,
    [ReceiverAccountNumber]   NVARCHAR (50)  NULL,
    [ReceiverHeadName]        NVARCHAR (50)  NULL,
    [ReceiverAccountantName]  NVARCHAR (50)  NULL,
    [ReceiverResponsibleName] NVARCHAR (50)  NULL,
    [RetransferSum]           NVARCHAR (50)  NULL,
    [RetransferTextSum]       NVARCHAR (50)  NULL,
    [RetransferTotal]         FLOAT (53)     NULL,
    [RetransferStatusId]      INT            NULL,
    CONSTRAINT [PK_Retransfer] PRIMARY KEY CLUSTERED ([RetransferId] ASC),
    CONSTRAINT [FK_Retransfer_BaseDocument] FOREIGN KEY ([BaseDocumentId]) REFERENCES [dbo].[BaseDocument] ([BaseDocumentId]),
    CONSTRAINT [FK_Retransfer_Organization] FOREIGN KEY ([ReceiverOrganizationId]) REFERENCES [dbo].[Organization] ([OrganizationId]),
    CONSTRAINT [FK_Retransfer_Organization1] FOREIGN KEY ([SenderOrganizationId]) REFERENCES [dbo].[Organization] ([OrganizationId]),
    CONSTRAINT [FK_Retransfer_RetransferStatus] FOREIGN KEY ([RetransferStatusId]) REFERENCES [dbo].[RetransferStatus] ([RetransferStatusId])
);

