//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationPlacementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganizationPlacementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrganizationPlacementResource", typeof(OrganizationPlacementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conciliation date.
        /// </summary>
        public static string ConciliationDate {
            get {
                return ResourceManager.GetString("ConciliationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can confirm the records thats have a status of &quot;Satisfy&quot;..
        /// </summary>
        public static string ConfirmationAlert {
            get {
                return ResourceManager.GetString("ConfirmationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New placement.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previous Date is empty.
        /// </summary>
        public static string DateErrorMessage {
            get {
                return ResourceManager.GetString("DateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feady for delivery date.
        /// </summary>
        public static string FeadyForDeliveryDate {
            get {
                return ResourceManager.GetString("FeadyForDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement entry.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering Organization.
        /// </summary>
        public static string OrderOrganization {
            get {
                return ResourceManager.GetString("OrderOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        public static string Organization_Title {
            get {
                return ResourceManager.GetString("Organization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placements.
        /// </summary>
        public static string Placement_Title {
            get {
                return ResourceManager.GetString("Placement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Date.
        /// </summary>
        public static string PlacementDate {
            get {
                return ResourceManager.GetString("PlacementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Մուտքագրում պահեստ» կարելի է տալ այն գրառմանը, որն ունի «Պահեստից ստացված» կարգավճակ:.
        /// </summary>
        public static string ReceiveAlert {
            get {
                return ResourceManager.GetString("ReceiveAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Date.
        /// </summary>
        public static string ReceiveDate {
            get {
                return ResourceManager.GetString("ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot represent the record that have the status.
        /// </summary>
        public static string RepresentAlert {
            get {
                return ResourceManager.GetString("RepresentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement representation.
        /// </summary>
        public static string Representation {
            get {
                return ResourceManager.GetString("Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfaction date.
        /// </summary>
        public static string SatisfactionDate {
            get {
                return ResourceManager.GetString("SatisfactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
    }
}
