//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlacementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlacementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PlacementResources", typeof(PlacementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Համաձայնեցման ա/թ.
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ճշտման ա/թ.
        /// </summary>
        public static string CorrectionDate {
            get {
                return ResourceManager.GetString("CorrectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կցված է.
        /// </summary>
        public static string IsTransfer {
            get {
                return ResourceManager.GetString("IsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրող հիմնարկի կոդ.
        /// </summary>
        public static string OrderOrganizationCode {
            get {
                return ResourceManager.GetString("OrderOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրող հիմնարկ.
        /// </summary>
        public static string OrderOrganizationId {
            get {
                return ResourceManager.GetString("OrderOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրող հիմնարկ.
        /// </summary>
        public static string OrderOrganizationName {
            get {
                return ResourceManager.GetString("OrderOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ներկայացնող հիմնարկի կոդ.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հիմնարկ.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ներկայացնող հիմնարկ.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Փաստաթղիթ հիմքի ա/թ.
        /// </summary>
        public static string PlacementBaseDate {
            get {
                return ResourceManager.GetString("PlacementBaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Փաստաթղթի հիմք.
        /// </summary>
        public static string PlacementBaseId {
            get {
                return ResourceManager.GetString("PlacementBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Փաստաթղիթ հիմք.
        /// </summary>
        public static string PlacementBaseName {
            get {
                return ResourceManager.GetString("PlacementBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հավելյալ.
        /// </summary>
        public static string PlacementBaseText {
            get {
                return ResourceManager.GetString("PlacementBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ներկայացման ա/թ.
        /// </summary>
        public static string PlacementDate {
            get {
                return ResourceManager.GetString("PlacementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հ/Հ.
        /// </summary>
        public static string PlacementId {
            get {
                return ResourceManager.GetString("PlacementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ապրանք.
        /// </summary>
        public static string PlacementItems {
            get {
                return ResourceManager.GetString("PlacementItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կարգավիճակ.
        /// </summary>
        public static string PlacementStatusId {
            get {
                return ResourceManager.GetString("PlacementStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կարգավիճակ.
        /// </summary>
        public static string PlacementStatusName {
            get {
                return ResourceManager.GetString("PlacementStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Առաքման պատրաստ ա/թ.
        /// </summary>
        public static string ReadyDate {
            get {
                return ResourceManager.GetString("ReadyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հիմնարկի պահեստի մուտքի ա/թ.
        /// </summary>
        public static string ReceiveDate {
            get {
                return ResourceManager.GetString("ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պահեստից ստացման ա/թ.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պահեստ.
        /// </summary>
        public static string StorageOrganizationId {
            get {
                return ResourceManager.GetString("StorageOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հիմնական պահեստ.
        /// </summary>
        public static string StorageOrganizationName {
            get {
                return ResourceManager.GetString("StorageOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաշիվ-ապրանքագիր.
        /// </summary>
        public static string TransferId {
            get {
                return ResourceManager.GetString("TransferId", resourceCulture);
            }
        }
    }
}
