//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Replacement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Replacement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Replacement", typeof(Replacement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Replacement_Base {
            get {
                return ResourceManager.GetString("Replacement_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base date.
        /// </summary>
        public static string Replacement_BaseDate {
            get {
                return ResourceManager.GetString("Replacement_BaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Replacement_BaseText {
            get {
                return ResourceManager.GetString("Replacement_BaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm date.
        /// </summary>
        public static string Replacement_ConfirmDate {
            get {
                return ResourceManager.GetString("Replacement_ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm organization.
        /// </summary>
        public static string Replacement_ConfirmOrganization {
            get {
                return ResourceManager.GetString("Replacement_ConfirmOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement date.
        /// </summary>
        public static string Replacement_Date {
            get {
                return ResourceManager.GetString("Replacement_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination organization.
        /// </summary>
        public static string Replacement_DestinationOrganization {
            get {
                return ResourceManager.GetString("Replacement_DestinationOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement&apos;s details.
        /// </summary>
        public static string Replacement_Details_Title {
            get {
                return ResourceManager.GetString("Replacement_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is transfer.
        /// </summary>
        public static string Replacement_IsTransfer {
            get {
                return ResourceManager.GetString("Replacement_IsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Replacement_OrganizationName {
            get {
                return ResourceManager.GetString("Replacement_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Replacement_Product {
            get {
                return ResourceManager.GetString("Replacement_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product entry.
        /// </summary>
        public static string Replacement_ProductEntry {
            get {
                return ResourceManager.GetString("Replacement_ProductEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Տարամադրել պահեստից» կարելի է այն գրառումը,
        ///
        ///որն ունի «Առաքման պատրաստ» կարգավիճակ:.
        /// </summary>
        public static string Replacement_ProvideReplacement_Alert {
            get {
                return ResourceManager.GetString("Replacement_ProvideReplacement_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string Replacement_ProvisionDate {
            get {
                return ResourceManager.GetString("Replacement_ProvisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready date.
        /// </summary>
        public static string Replacement_ReadyDate {
            get {
                return ResourceManager.GetString("Replacement_ReadyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive date.
        /// </summary>
        public static string Replacement_ReceiveDate {
            get {
                return ResourceManager.GetString("Replacement_ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of entry to storage.
        /// </summary>
        public static string Replacement_ReceiveDateStorage {
            get {
                return ResourceManager.GetString("Replacement_ReceiveDateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Replacement_ReplacementStatus {
            get {
                return ResourceManager.GetString("Replacement_ReplacementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Replacement_ReplacementSum {
            get {
                return ResourceManager.GetString("Replacement_ReplacementSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source organization.
        /// </summary>
        public static string Replacement_SourceOrganization {
            get {
                return ResourceManager.GetString("Replacement_SourceOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply from storage.
        /// </summary>
        public static string Replacement_SupplyStorage {
            get {
                return ResourceManager.GetString("Replacement_SupplyStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement.
        /// </summary>
        public static string Replacement_Title {
            get {
                return ResourceManager.GetString("Replacement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement - confirmation.
        /// </summary>
        public static string ReplacementConfirm_Title {
            get {
                return ResourceManager.GetString("ReplacementConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement - Entry.
        /// </summary>
        public static string ReplacementEntry_Title {
            get {
                return ResourceManager.GetString("ReplacementEntry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ReplacementProduct_Id {
            get {
                return ResourceManager.GetString("ReplacementProduct_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item quantity.
        /// </summary>
        public static string ReplacementProduct_ItemQuantity {
            get {
                return ResourceManager.GetString("ReplacementProduct_ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ReplacementProduct_Quantity {
            get {
                return ResourceManager.GetString("ReplacementProduct_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        public static string ReplacementProduct_TotalCost {
            get {
                return ResourceManager.GetString("ReplacementProduct_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit cost.
        /// </summary>
        public static string ReplacementProduct_UnitCost {
            get {
                return ResourceManager.GetString("ReplacementProduct_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned product entry.
        /// </summary>
        public static string ReplacementStorage_Title {
            get {
                return ResourceManager.GetString("ReplacementStorage_Title", resourceCulture);
            }
        }
    }
}
