//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsDrugClass {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsDrugClass() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsDrugClass", typeof(rsDrugClass).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug category.
        /// </summary>
        public static string DrugCategoryId {
            get {
                return ResourceManager.GetString("DrugCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug category.
        /// </summary>
        public static string DrugCategoryName {
            get {
                return ResourceManager.GetString("DrugCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DrugClassId {
            get {
                return ResourceManager.GetString("DrugClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DrugClassName {
            get {
                return ResourceManager.GetString("DrugClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DrugClassStatus {
            get {
                return ResourceManager.GetString("DrugClassStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string DrugId {
            get {
                return ResourceManager.GetString("DrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DrugName {
            get {
                return ResourceManager.GetString("DrugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Type.
        /// </summary>
        public static string DrugSourceId {
            get {
                return ResourceManager.GetString("DrugSourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Type.
        /// </summary>
        public static string DrugSourceName {
            get {
                return ResourceManager.GetString("DrugSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string DrugStatus {
            get {
                return ResourceManager.GetString("DrugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug type.
        /// </summary>
        public static string DrugTypeId {
            get {
                return ResourceManager.GetString("DrugTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug type.
        /// </summary>
        public static string DrugTypeName {
            get {
                return ResourceManager.GetString("DrugTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string FileId {
            get {
                return ResourceManager.GetString("FileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic name.
        /// </summary>
        public static string GenericName {
            get {
                return ResourceManager.GetString("GenericName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item qantity.
        /// </summary>
        public static string ItemQuantity {
            get {
                return ResourceManager.GetString("ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductCategoryId {
            get {
                return ResourceManager.GetString("ProductCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ProductCategoryName {
            get {
                return ResourceManager.GetString("ProductCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ProductGroupId {
            get {
                return ResourceManager.GetString("ProductGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ProductGroupName {
            get {
                return ResourceManager.GetString("ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProductTypeId {
            get {
                return ResourceManager.GetString("ProductTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProductTypeName {
            get {
                return ResourceManager.GetString("ProductTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seria.
        /// </summary>
        public static string Seria {
            get {
                return ResourceManager.GetString("Seria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageId {
            get {
                return ResourceManager.GetString("StorageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store օrganization.
        /// </summary>
        public static string StoreOrganizationCode {
            get {
                return ResourceManager.GetString("StoreOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store օrganization.
        /// </summary>
        public static string StoreOrganizationId {
            get {
                return ResourceManager.GetString("StoreOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store օrganization.
        /// </summary>
        public static string StoreOrganizationName {
            get {
                return ResourceManager.GetString("StoreOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierId {
            get {
                return ResourceManager.GetString("SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Item Quantity.
        /// </summary>
        public static string UnitItemQuantity {
            get {
                return ResourceManager.GetString("UnitItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type.
        /// </summary>
        public static string UnitTypeId {
            get {
                return ResourceManager.GetString("UnitTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit type.
        /// </summary>
        public static string UnitTypeName {
            get {
                return ResourceManager.GetString("UnitTypeName", resourceCulture);
            }
        }
    }
}
