//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsJunkConsumption {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsJunkConsumption() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsJunkConsumption", typeof(rsJunkConsumption).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item quantity.
        /// </summary>
        public static string ItemQuantity {
            get {
                return ResourceManager.GetString("ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string JunkBaseId {
            get {
                return ResourceManager.GetString("JunkBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string JunkBaseName {
            get {
                return ResourceManager.GetString("JunkBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Date.
        /// </summary>
        public static string JunkConsumptionDate {
            get {
                return ResourceManager.GetString("JunkConsumptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junk Product.
        /// </summary>
        public static string JunkConsumptionId {
            get {
                return ResourceManager.GetString("JunkConsumptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string JunkConsumptionStatusId {
            get {
                return ResourceManager.GetString("JunkConsumptionStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string JunkConsumptionStatusName {
            get {
                return ResourceManager.GetString("JunkConsumptionStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization_Name {
            get {
                return ResourceManager.GetString("Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
    }
}
