//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsOrganization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsOrganization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsOrganization", typeof(rsOrganization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounter Name.
        /// </summary>
        public static string AccountantName {
            get {
                return ResourceManager.GetString("AccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BankId {
            get {
                return ResourceManager.GetString("BankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Location.
        /// </summary>
        public static string DeliveryLocation {
            get {
                return ResourceManager.GetString("DeliveryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goverment.
        /// </summary>
        public static string GovermentId {
            get {
                return ResourceManager.GetString("GovermentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goverment.
        /// </summary>
        public static string GovermentName {
            get {
                return ResourceManager.GetString("GovermentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Name.
        /// </summary>
        public static string HeadName {
            get {
                return ResourceManager.GetString("HeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goverment.
        /// </summary>
        public static string IsGoverment {
            get {
                return ResourceManager.GetString("IsGoverment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string IsOrganization {
            get {
                return ResourceManager.GetString("IsOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string IsRegion {
            get {
                return ResourceManager.GetString("IsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string IsStorage {
            get {
                return ResourceManager.GetString("IsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OrganizationLocation {
            get {
                return ResourceManager.GetString("OrganizationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionId {
            get {
                return ResourceManager.GetString("RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionName {
            get {
                return ResourceManager.GetString("RegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Name.
        /// </summary>
        public static string ResponsibleName {
            get {
                return ResourceManager.GetString("ResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Code.
        /// </summary>
        public static string StorageCode {
            get {
                return ResourceManager.GetString("StorageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageId {
            get {
                return ResourceManager.GetString("StorageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Identification Number.
        /// </summary>
        public static string TinNumber {
            get {
                return ResourceManager.GetString("TinNumber", resourceCulture);
            }
        }
    }
}
