//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsRetransfer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsRetransfer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsRetransfer", typeof(rsRetransfer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string BaseDocumentId {
            get {
                return ResourceManager.GetString("BaseDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string BaseDocumentName {
            get {
                return ResourceManager.GetString("BaseDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string DealInfo {
            get {
                return ResourceManager.GetString("DealInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Accountant.
        /// </summary>
        public static string ReceiverAccountant {
            get {
                return ResourceManager.GetString("ReceiverAccountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver account number.
        /// </summary>
        public static string ReceiverAccountNumber {
            get {
                return ResourceManager.GetString("ReceiverAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver bank.
        /// </summary>
        public static string ReceiverBankName {
            get {
                return ResourceManager.GetString("ReceiverBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Head.
        /// </summary>
        public static string ReceiverHead {
            get {
                return ResourceManager.GetString("ReceiverHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Location.
        /// </summary>
        public static string ReceiverLocation {
            get {
                return ResourceManager.GetString("ReceiverLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationCode {
            get {
                return ResourceManager.GetString("ReceiverOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationId {
            get {
                return ResourceManager.GetString("ReceiverOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationName {
            get {
                return ResourceManager.GetString("ReceiverOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Name.
        /// </summary>
        public static string ReceiverResponsibleName {
            get {
                return ResourceManager.GetString("ReceiverResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver supply location.
        /// </summary>
        public static string ReceiverSupplyLocation {
            get {
                return ResourceManager.GetString("ReceiverSupplyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver TIN.
        /// </summary>
        public static string ReceiverTin {
            get {
                return ResourceManager.GetString("ReceiverTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RetransferDate {
            get {
                return ResourceManager.GetString("RetransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RetransferStatusCode {
            get {
                return ResourceManager.GetString("RetransferStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RetransferStatusId {
            get {
                return ResourceManager.GetString("RetransferStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RetransferStatusName {
            get {
                return ResourceManager.GetString("RetransferStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string RetransferTotal {
            get {
                return ResourceManager.GetString("RetransferTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Accountant.
        /// </summary>
        public static string SenderAccountantName {
            get {
                return ResourceManager.GetString("SenderAccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender account number.
        /// </summary>
        public static string SenderAccountNumber {
            get {
                return ResourceManager.GetString("SenderAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Bank.
        /// </summary>
        public static string SenderBankName {
            get {
                return ResourceManager.GetString("SenderBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Head.
        /// </summary>
        public static string SenderHeadName {
            get {
                return ResourceManager.GetString("SenderHeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Location.
        /// </summary>
        public static string SenderLocation {
            get {
                return ResourceManager.GetString("SenderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationCode {
            get {
                return ResourceManager.GetString("SenderOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationId {
            get {
                return ResourceManager.GetString("SenderOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationName {
            get {
                return ResourceManager.GetString("SenderOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Responsible.
        /// </summary>
        public static string SenderResponsibleName {
            get {
                return ResourceManager.GetString("SenderResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender supply location.
        /// </summary>
        public static string SenderSupplyLocation {
            get {
                return ResourceManager.GetString("SenderSupplyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender TIN.
        /// </summary>
        public static string SenderTin {
            get {
                return ResourceManager.GetString("SenderTin", resourceCulture);
            }
        }
    }
}
