//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsReplacement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsReplacement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsReplacement", typeof(rsReplacement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm date.
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm organization.
        /// </summary>
        public static string ConfirmOrganizationCode {
            get {
                return ResourceManager.GetString("ConfirmOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm organization.
        /// </summary>
        public static string ConfirmOrganizationId {
            get {
                return ResourceManager.GetString("ConfirmOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm organization.
        /// </summary>
        public static string ConfirmOrganizationName {
            get {
                return ResourceManager.GetString("ConfirmOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement - confirmation.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination organization.
        /// </summary>
        public static string DestinationOrganizationCode {
            get {
                return ResourceManager.GetString("DestinationOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination organization.
        /// </summary>
        public static string DestinationOrganizationId {
            get {
                return ResourceManager.GetString("DestinationOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination organization.
        /// </summary>
        public static string DestinationOrganizationName {
            get {
                return ResourceManager.GetString("DestinationOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement&apos;s details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement - Entry.
        /// </summary>
        public static string EntryTitle {
            get {
                return ResourceManager.GetString("EntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Retransfer.
        /// </summary>
        public static string IsRetransfer {
            get {
                return ResourceManager.GetString("IsRetransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item quantity.
        /// </summary>
        public static string ItemQuantity {
            get {
                return ResourceManager.GetString("ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product entry.
        /// </summary>
        public static string ProductEntry {
            get {
                return ResourceManager.GetString("ProductEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Date.
        /// </summary>
        public static string ProvisionDate {
            get {
                return ResourceManager.GetString("ProvisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Date.
        /// </summary>
        public static string ReadyDate {
            get {
                return ResourceManager.GetString("ReadyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Date.
        /// </summary>
        public static string ReceiveDate {
            get {
                return ResourceManager.GetString("ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data of entry to storage.
        /// </summary>
        public static string ReceiveDateStorage {
            get {
                return ResourceManager.GetString("ReceiveDateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Date.
        /// </summary>
        public static string ReplacementBaseDate {
            get {
                return ResourceManager.GetString("ReplacementBaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string ReplacementBaseId {
            get {
                return ResourceManager.GetString("ReplacementBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string ReplacementBaseName {
            get {
                return ResourceManager.GetString("ReplacementBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ReplacementBaseText {
            get {
                return ResourceManager.GetString("ReplacementBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement date.
        /// </summary>
        public static string ReplacementDate {
            get {
                return ResourceManager.GetString("ReplacementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReplacementStatusCode {
            get {
                return ResourceManager.GetString("ReplacementStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReplacementStatusId {
            get {
                return ResourceManager.GetString("ReplacementStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ReplacementStatusName {
            get {
                return ResourceManager.GetString("ReplacementStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned product entry.
        /// </summary>
        public static string ReplacementStorageTitle {
            get {
                return ResourceManager.GetString("ReplacementStorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string ReplacementSum {
            get {
                return ResourceManager.GetString("ReplacementSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retransfer Date.
        /// </summary>
        public static string RetransferDate {
            get {
                return ResourceManager.GetString("RetransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retransfer.
        /// </summary>
        public static string RetransferId {
            get {
                return ResourceManager.GetString("RetransferId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source organization.
        /// </summary>
        public static string SourceOrganizationCode {
            get {
                return ResourceManager.GetString("SourceOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source organization.
        /// </summary>
        public static string SourceOrganizationId {
            get {
                return ResourceManager.GetString("SourceOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source organization.
        /// </summary>
        public static string SourceOrganizationName {
            get {
                return ResourceManager.GetString("SourceOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Storage.
        /// </summary>
        public static string StorageId {
            get {
                return ResourceManager.GetString("StorageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply from storage.
        /// </summary>
        public static string SupplyStorage {
            get {
                return ResourceManager.GetString("SupplyStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string UnitCost {
            get {
                return ResourceManager.GetString("UnitCost", resourceCulture);
            }
        }
    }
}
