//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsTransfer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsTransfer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rsTransfer", typeof(rsTransfer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string BaseDocumentId {
            get {
                return ResourceManager.GetString("BaseDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string BaseDocumentName {
            get {
                return ResourceManager.GetString("BaseDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Date.
        /// </summary>
        public static string ConfirmDate {
            get {
                return ResourceManager.GetString("ConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Date.
        /// </summary>
        public static string CorrectionDate {
            get {
                return ResourceManager.GetString("CorrectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string DealInfo {
            get {
                return ResourceManager.GetString("DealInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsTransfer.
        /// </summary>
        public static string IsTransfer {
            get {
                return ResourceManager.GetString("IsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Organization.
        /// </summary>
        public static string OrderOrganizationCode {
            get {
                return ResourceManager.GetString("OrderOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Organization.
        /// </summary>
        public static string OrderOrganizationId {
            get {
                return ResourceManager.GetString("OrderOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Organization.
        /// </summary>
        public static string OrderOrganizationName {
            get {
                return ResourceManager.GetString("OrderOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationCode {
            get {
                return ResourceManager.GetString("OrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Date.
        /// </summary>
        public static string PlacementBaseDate {
            get {
                return ResourceManager.GetString("PlacementBaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string PlacementBaseId {
            get {
                return ResourceManager.GetString("PlacementBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string PlacementBaseName {
            get {
                return ResourceManager.GetString("PlacementBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PlacementBaseText {
            get {
                return ResourceManager.GetString("PlacementBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Date.
        /// </summary>
        public static string PlacementDate {
            get {
                return ResourceManager.GetString("PlacementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement.
        /// </summary>
        public static string PlacementId {
            get {
                return ResourceManager.GetString("PlacementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PlacementStatusId {
            get {
                return ResourceManager.GetString("PlacementStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PlacementStatusName {
            get {
                return ResourceManager.GetString("PlacementStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready Date.
        /// </summary>
        public static string ReadyDate {
            get {
                return ResourceManager.GetString("ReadyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Date.
        /// </summary>
        public static string ReceiveDate {
            get {
                return ResourceManager.GetString("ReceiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Accountant.
        /// </summary>
        public static string ReceiverAccountantName {
            get {
                return ResourceManager.GetString("ReceiverAccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver account number.
        /// </summary>
        public static string ReceiverAccountNumber {
            get {
                return ResourceManager.GetString("ReceiverAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver bank.
        /// </summary>
        public static string ReceiverBankName {
            get {
                return ResourceManager.GetString("ReceiverBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Head.
        /// </summary>
        public static string ReceiverHeadName {
            get {
                return ResourceManager.GetString("ReceiverHeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver location.
        /// </summary>
        public static string ReceiverLocation {
            get {
                return ResourceManager.GetString("ReceiverLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationCode {
            get {
                return ResourceManager.GetString("ReceiverOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationId {
            get {
                return ResourceManager.GetString("ReceiverOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver organization.
        /// </summary>
        public static string ReceiverOrganizationName {
            get {
                return ResourceManager.GetString("ReceiverOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Responsible.
        /// </summary>
        public static string ReceiverResponsibleName {
            get {
                return ResourceManager.GetString("ReceiverResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver supply location.
        /// </summary>
        public static string ReceiverSupplyLocation {
            get {
                return ResourceManager.GetString("ReceiverSupplyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver TIN.
        /// </summary>
        public static string ReceiverTin {
            get {
                return ResourceManager.GetString("ReceiverTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Accountant.
        /// </summary>
        public static string SenderAccountantName {
            get {
                return ResourceManager.GetString("SenderAccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender account number.
        /// </summary>
        public static string SenderAccountNumber {
            get {
                return ResourceManager.GetString("SenderAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender bank.
        /// </summary>
        public static string SenderBankName {
            get {
                return ResourceManager.GetString("SenderBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Head.
        /// </summary>
        public static string SenderHeadName {
            get {
                return ResourceManager.GetString("SenderHeadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender location.
        /// </summary>
        public static string SenderLocation {
            get {
                return ResourceManager.GetString("SenderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationCode {
            get {
                return ResourceManager.GetString("SenderOrganizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationId {
            get {
                return ResourceManager.GetString("SenderOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender organization.
        /// </summary>
        public static string SenderOrganizationName {
            get {
                return ResourceManager.GetString("SenderOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Responsible.
        /// </summary>
        public static string SenderResponsibleName {
            get {
                return ResourceManager.GetString("SenderResponsibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender supply location.
        /// </summary>
        public static string SenderSupplyLocation {
            get {
                return ResourceManager.GetString("SenderSupplyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender TIN.
        /// </summary>
        public static string SenderTin {
            get {
                return ResourceManager.GetString("SenderTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageOrganizationId {
            get {
                return ResourceManager.GetString("StorageOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageOrganizationName {
            get {
                return ResourceManager.GetString("StorageOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TransferId {
            get {
                return ResourceManager.GetString("TransferId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached placements.
        /// </summary>
        public static string TransferPlacement {
            get {
                return ResourceManager.GetString("TransferPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TransferStatusCode {
            get {
                return ResourceManager.GetString("TransferStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TransferStatusId {
            get {
                return ResourceManager.GetString("TransferStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TransferStatusName {
            get {
                return ResourceManager.GetString("TransferStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string TransferSum {
            get {
                return ResourceManager.GetString("TransferSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Sum.
        /// </summary>
        public static string TransferTextSum {
            get {
                return ResourceManager.GetString("TransferTextSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TransferTotal {
            get {
                return ResourceManager.GetString("TransferTotal", resourceCulture);
            }
        }
    }
}
